### ISSUE TITLE
Power pin out

### ISSUE THREAD

**Issue by nerdalertdk** [Ragebone/nr64_supermicro_x10sle-f#1]
Hi

Could you svare the power pin out if you also have those?

💪🏻

**Comment by Ragebone** [comment]
what exactly do you mean with "power pinout" ? 

if it is the 8Pin EPS, it is exactly as the colors on the cable show. 
Yellow is 12V, purple 5VSB.

**Comment by Ragebone** [comment]
added a better explanation to the power-supply document. 
So i guess this can be closed.
